# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-10 12:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0090_schema_merchant_tx_confidence'),
        ('wallet', '0003_schema_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=6, unique=True, verbose_name='UID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coin_type', models.PositiveSmallIntegerField(choices=[(0, 'Bitcoin'), (1, 'Bitcoin Testnet')])),
                ('merchant_coin_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('fee_coin_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('paid_coin_amount', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('refund_address', models.CharField(max_length=35, null=True)),
                ('incoming_tx_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None)),
                ('refund_tx_id', models.CharField(max_length=64, null=True)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'BIP 0021 (Bitcoin URI)'), (2, 'BIP 0070 (Payment Protocol)')], null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_received', models.DateTimeField(null=True)),
                ('time_notified', models.DateTimeField(null=True)),
                ('time_confirmed', models.DateTimeField(null=True)),
                ('time_refunded', models.DateTimeField(null=True)),
                ('time_cancelled', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Currency')),
                ('deposit_address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='wallet.Address')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Device')),
            ],
        ),
    ]
