# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-17 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0090_schema_merchant_tx_confidence'),
        ('transactions', '0004_data_create_bchanges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=6, unique=True, verbose_name='UID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coin_type', models.PositiveSmallIntegerField(choices=[(0, 'Bitcoin'), (1, 'Bitcoin Testnet')])),
                ('customer_coin_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('tx_fee_coin_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('customer_address', models.CharField(max_length=35, null=True)),
                ('outgoing_tx_id', models.CharField(max_length=64, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_sent', models.DateTimeField(null=True)),
                ('time_broadcasted', models.DateTimeField(null=True)),
                ('time_notified', models.DateTimeField(null=True)),
                ('time_confirmed', models.DateTimeField(null=True)),
                ('time_cancelled', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Currency')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Device')),
            ],
        ),
    ]
