# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-18 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_schema_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancechange',
            name='withdrawal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.Withdrawal'),
        ),
        migrations.AlterField(
            model_name='balancechange',
            name='deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.Deposit'),
        ),
    ]
