# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-25 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_schema_bchange_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancechange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 25, 12, 10, 50, 204374, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
