# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-30 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_schema_bchange_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='refund_coin_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
