# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-01 08:10
from __future__ import unicode_literals

from django.db import migrations


def update_deposits(apps, schema_editor):
    Deposit = apps.get_model('transactions', 'Deposit')
    for deposit in Deposit.objects.filter(time_refunded__isnull=False):
        deposit.refund_coin_amount = deposit.paid_coin_amount
        deposit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_schema_deposit_refund_coin_amount'),
    ]

    operations = [
        migrations.RunPython(update_deposits,
                             migrations.RunPython.noop),
    ]
