# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-06 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0092_data_currency_is_fiat'),
        ('transactions', '0010_schema_deposit_rm_time_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='coin',
            field=models.ForeignKey(help_text='Crypto currency used for transaction processing.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='website.Currency'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='coin',
            field=models.ForeignKey(help_text='Crypto currency used for transaction processing.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='website.Currency'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Display amount'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='website.Currency', verbose_name='Display currency'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Display amount'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='website.Currency', verbose_name='Display currency'),
        ),
    ]
