# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-06 14:03
from __future__ import unicode_literals

from django.db import migrations
from wallet.constants import BIP44_COIN_TYPES


def set_coin(apps, schema_editor):
    Currency = apps.get_model('website', 'Currency')
    coins = {
        0: Currency.objects.get(name='BTC'),
        1: Currency.objects.get(name='TBTC'),
    }
    Deposit = apps.get_model('transactions', 'Deposit')
    for deposit in Deposit.objects.all():
        deposit.coin = coins[deposit.coin_type]
        deposit.save()
    Withdrawal = apps.get_model('transactions', 'Withdrawal')
    for withdrawal in Withdrawal.objects.all():
        withdrawal.coin = coins[withdrawal.coin_type]
        withdrawal.save()


def reset_coin(apps, schema_editor):
    Deposit = apps.get_model('transactions', 'Deposit')
    Deposit.objects.all().update(coin=None)
    Withdrawal = apps.get_model('transactions', 'Withdrawal')
    Withdrawal.objects.all().update(coin=None)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_schema_transaction_coin'),
    ]

    operations = [
        migrations.RunPython(set_coin, reset_coin),
    ]
