# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_schema_transaction_rm_coin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BIP 0021 (Payment URI)'), (2, 'BIP 0070 (Payment Protocol)')], null=True),
        ),
    ]
