vm:
  memory: 2048
  cpus: 2
  disk: 30GB
  ports:
    postgresql: 5432
    redis: 6379
    bitcoind: 18332
    dashd: 19998
    sentry: 9000
    xbt-server: 8083

pillar:
  postgresql:
    user: xbt
    password: xbt
    createdb: true
    database: xbt
  bitcoind:
    user: xbt
    password: xbt
  dashd:
    user: xbt
    password: xbt
  sentry:
    smtp_host: localhost
    smtp_port: 25
    smtp_user: user
    smtp_password: password
