vm:
  memory: 2048
  cpus: 1
  ports:
    postgresql: 5432
    redis: 6379
    bitcoind: 18332
    sentry: 9000
    xbt-server: 8083

pillar:
  postgresql:
    user: xbt
    password: xbt
    createdb: true
    database: xbt
  bitcoind:
    user: xbt
    password: xbt
