# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-14 19:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0080_data_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='system_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
