# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 20:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0081_schema_device_system_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='system_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
