# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-28 12:18
from __future__ import unicode_literals

from django.db import migrations

def set_max_payout(apps, schema_editor):
    Device = apps.get_model('website', 'Device')
    for device in Device.objects.filter(account__isnull=False):
        device.max_payout = device.account.currency.max_payout
        device.save()

def unset_max_payout(apps, schema_editor):
    Device = apps.get_model('website', 'Device')
    for device in Device.objects.all():
        device.max_payout = None
        device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0084_schema_device_max_payout'),
    ]

    operations = [
        migrations.RunPython(set_max_payout,
                             unset_max_payout),
    ]
