# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-09 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0086_schema_account_rm_max_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantaccount',
            name='activation_code',
            field=models.CharField(editable=False, max_length=6, null=True, unique=True),
        ),
    ]
