# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0088_data_merchant_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantaccount',
            name='activation_code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
