# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-10 13:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0089_schema_merchant_activation_code_nn'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantaccount',
            name='tx_confidence_threshold',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='TX confidence threshold'),
        ),
    ]
