# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0090_schema_merchant_tx_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_fiat',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
