# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-06 13:39
from __future__ import unicode_literals

from django.db import migrations
from website.fixtures.currencies import update_currencies


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0091_schema_currency_is_fiat'),
    ]

    operations = [
        migrations.RunPython(update_currencies,
                             migrations.RunPython.noop),
    ]
