# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-09 17:41
from __future__ import unicode_literals

from django.db import migrations
from website.fixtures.currencies import update_currencies


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0093_data_device_change_account'),
    ]

    operations = [
        migrations.RunPython(update_currencies,
                             migrations.RunPython.noop),
    ]
