# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-31 10:33
from __future__ import unicode_literals

from django.db import migrations
from website.fixtures.currencies import update_currencies


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0095_schema_currency_is_enabled'),
    ]

    operations = [
        migrations.RunPython(update_currencies,
                             migrations.RunPython.noop),
    ]
