# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-07 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.PositiveSmallIntegerField(choices=[(0, 'Bitcoin'), (1, 'Bitcoin Testnet')], unique=True)),
                ('private_key', models.CharField(help_text='Private key, WIF', max_length=120, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
