# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('parent_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.WalletKey')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='walletaccount',
            unique_together=set([('parent_key', 'index')]),
        ),
    ]
