# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_schema_walletaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_change', models.BooleanField()),
                ('index', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=50, unique=True)),
                ('wallet_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.WalletAccount')),
            ],
            options={
                'ordering': ['wallet_account', 'is_change', 'index'],
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('wallet_account', 'is_change', 'index')]),
        ),
    ]
