# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-10 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_schema_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletkey',
            name='coin_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Bitcoin'), (5, 'Dash'), (1, 'Bitcoin Testnet'), (1005, 'Dash Testnet')], unique=True),
        ),
    ]
