# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0035_schema_fix_typo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawalorder',
            old_name='time_completed',
            new_name='time_notified',
        ),
    ]
