# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0036_schema_wo_rename_time_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalorder',
            name='time_confirmed',
            field=models.DateTimeField(null=True),
        ),
    ]
