# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 12:08
from __future__ import unicode_literals

from django.db import migrations


def fill_time_confirmed(apps, schema_editor):
    WithdrawalOrder = apps.get_model('operations', 'WithdrawalOrder')
    for order in WithdrawalOrder.objects.filter(time_notified__isnull=False):
        order.time_confirmed = order.time_notified
        order.save()


def remove_time_confirmed(apps, schema_editor):
    WithdrawalOrder = apps.get_model('operations', 'WithdrawalOrder')
    for order in WithdrawalOrder.objects.all():
        order.time_confirmed = None
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0037_schema_wo_time_confirmed'),
    ]

    operations = [
        migrations.RunPython(fill_time_confirmed, remove_time_confirmed),
    ]
